#!/bin/bash
echo Usernames only, no email addresses
echo reading from resetpwlist.txt
echo Starting...


while read i; do


#grab first intial from last character in username, turn to lowercase
FIRST_I=$(echo $i | awk '{print substr($0,length,1)}' | tr '[:upper:]' '[:lower:]')
#echo variable, cut off first two digits, cut first character, turn to lowercase
LAST_I=$(echo $i | sed 's/..//' | cut -c-1 | tr '[:upper:]' '[:lower:]')
DEFAULTPW="$FIRST_I""$LAST_I""3456789"

echo $i
#echo $FIRST_I
#echo $LAST_I
echo $DEFAULTPW

gam update user $i password ''$DEFAULTPW'' changepassword off


done </Users/Havens/bin/resetpwlist.txt
